#!/bin/sh

# script/cibuild: Setup environment for CI to run tests. This is primarily
#                 designed to run on the continuous integration server.

set -e

cd "$(dirname "$0")/.."

# run tests
echo "Running tests ..."
date "+%H:%M:%S"

RUBYOPTS=--debug=frozen-string-literal

# run tests.
script/test

# run linters
script/linter
