#!/bin/sh

# script/linter: Run the linters for the project.

set -e

cd "$(dirname "$0")/.."

RUBYOPTS=--debug=frozen-string-literal

echo "==> Running rubocop..."
bundle exec rubocop

echo "==> Running scss-lint..."
bundle exec scss-lint
