#!/bin/sh

# script/server: Launch the application and any extra required processes
#                locally.

set -e

cd "$(dirname "$0")/.."

if [ -f "$(which docker-compose)" ]; then
  echo "===> Stopping existing containers..."
  docker-compose stop
fi

# ensure everything in the app is up to date.
script/update

test -z "$RACK_ENV" &&
  RACK_ENV='development'

# boot the app and any other necessary processes.
bundle exec foreman start -f Procfile.dev
