#!/bin/sh

# script/setup: Set up application for the first time after cloning, or set it
#               back to the initial first unused state.



set -e

cd "$(dirname "$0")/.."

if [ "$SELFCONTAINED" != "true" ]; then
  # If not self contained, set up docker and dependencies
  if [-f "$(which docker-compose)" ]; then
    echo "===> Removing existing containers..."
    docker-compose down
  fi

  script/bootstrap

  echo "===> Waiting for the containers to mount..."
  sleep 5
else
  # If we are self-contained, docker and dependencies are done, so check
  # on the port forwarding.
  unset BUNDLER_VERSION
  if ! pgrep -x 'rinetd' > /dev/null
  then
    rinetd
  fi
fi

echo "===> Preparing database..."
bin/rails db:setup

echo "===> Remove old logs and tempfiles..."
bin/rails log:clear tmp:clear

echo "===> Restart application server..."
bin/rails restart

if [ -z "$RAILS_ENV" ] && [ -z "$RACK_ENV" ]; then
  # Only things for a development environment will run inside here
  # Do things that need to be done to the application to set up for the first
  # time. Or things needed to be run to to reset the application back to first
  # use experience. These things are scoped to the application's domain.

  if ! [ -r ".env" ]; then
    cp .env-example .env
  fi
fi

echo "==> Your app is almost ready! Please make sure you fill out your .env file."
