#!/bin/sh

# script/update: Update application to run for its current checkout.

set -e

cd "$(dirname "$0")/.."

script/bootstrap

echo "===> Waiting for the containers to mount..."
sleep 5

echo "==> Updating database..."
bin/rake db:migrate db:test:prepare

echo "===> Remove old logs and tempfiles..."
bin/rails log:clear tmp:clear

echo "===> Restart application server..."
bin/rails restart
