#!/bin/sh

# script/update: Update application to run for its current checkout.

set -e

cd "$(dirname "$0")/.."

script/bootstrap

echo "==> Updating database..."
bin/rake db:migrate db:test:prepare
